CRITICAL - 2024-11-28 21:47:31 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "pagos/index.php"
[Method: GET, Route: pagos]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pagos/index.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('pagos/index', [], true)
 3 APPPATH\Controllers\PagoController.php(21): view('pagos/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 21:48:26 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "pagos/index.php"
[Method: GET, Route: pagos]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pagos/index.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('pagos/index', [], true)
 3 APPPATH\Controllers\PagoController.php(21): view('pagos/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 21:48:30 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "pagos/index.php"
[Method: GET, Route: pagos]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pagos/index.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('pagos/index', [], true)
 3 APPPATH\Controllers\PagoController.php(21): view('pagos/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 21:55:20 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "pagos/index.php"
[Method: GET, Route: pagos]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('pagos/index.php')
 2 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('pagos/index', [], true)
 3 APPPATH\Controllers\PagoController.php(21): view('pagos/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:03:19 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "plantilla_pagos.php"
[Method: GET, Route: pagos]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('plantilla_pagos.php')
 2 SYSTEMPATH\View\View.php(250): CodeIgniter\View\View->render('plantilla_pagos', [], true)
 3 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('pagos/index', [], true)
 4 APPPATH\Controllers\PagoController.php(21): view('pagos/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:08:41 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "plantilla_pagos.php"
[Method: GET, Route: pagos/create]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 41.
 1 SYSTEMPATH\View\View.php(222): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('plantilla_pagos.php')
 2 SYSTEMPATH\View\View.php(250): CodeIgniter\View\View->render('plantilla_pagos', [], true)
 3 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('pagos/create', [], true)
 4 APPPATH\Controllers\PagoController.php(35): view('pagos/create')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-28 22:09:39 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\laragon\www\pagos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\pagos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pa...', 0)
#1 D:\laragon\www\pagos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 D:\laragon\www\pagos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 D:\laragon\www\pagos\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 D:\laragon\www\pagos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\laragon\www\pagos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\laragon\www\pagos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\laragon\www\pagos\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\laragon\www\pagos\app\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save(Array)
#9 D:\laragon\www\pagos\system\CodeIgniter.php(933): App\Controllers\PagoController->store()
#10 D:\laragon\www\pagos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
#11 D:\laragon\www\pagos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\laragon\www\pagos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\laragon\www\pagos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\laragon\www\pagos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-28 22:09:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: pagos/store]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:09:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'1000\', \'24\', NULL, \'transferencia\', \'2024-11-28 22:09:39\', \'2024-11-28 22:09:39\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'1000\', \'24\', NULL, \'transferencia\', \'2024-11-28 22:09:39\', \'2024-11-28 22:09:39\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:09:39 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'1000\', \'24\', NULL, \'transferencia\', \'2024-11-28 22:09:39\', \'2024-11-28 22:09:39\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'1000\', \'24\', NULL, \'transferencia\', \'2024-11-28 22:09:39\', \'2024-11-28 22:09:39\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'1000\', \'24\', NULL, \'transferencia\', \'2024-11-28 22:09:39\', \'2024-11-28 22:09:39\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-28 22:11:19 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\laragon\www\pagos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\pagos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pa...', 0)
#1 D:\laragon\www\pagos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 D:\laragon\www\pagos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 D:\laragon\www\pagos\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 D:\laragon\www\pagos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\laragon\www\pagos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\laragon\www\pagos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\laragon\www\pagos\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\laragon\www\pagos\app\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save(Array)
#9 D:\laragon\www\pagos\system\CodeIgniter.php(933): App\Controllers\PagoController->store()
#10 D:\laragon\www\pagos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
#11 D:\laragon\www\pagos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\laragon\www\pagos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\laragon\www\pagos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\laragon\www\pagos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-28 22:11:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: pagos/store]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:11:19 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'1000\', \'23\', NULL, \'transferencia\', \'2024-11-28 22:11:19\', \'2024-11-28 22:11:19\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'1000\', \'23\', NULL, \'transferencia\', \'2024-11-28 22:11:19\', \'2024-11-28 22:11:19\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:11:19 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'1000\', \'23\', NULL, \'transferencia\', \'2024-11-28 22:11:19\', \'2024-11-28 22:11:19\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'1000\', \'23\', NULL, \'transferencia\', \'2024-11-28 22:11:19\', \'2024-11-28 22:11:19\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'1000\', \'23\', NULL, \'transferencia\', \'2024-11-28 22:11:19\', \'2024-11-28 22:11:19\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:13:54 --> ParseError: syntax error, unexpected single-quoted string "created_at", expecting "]"
[Method: POST, Route: pagos/store]
in APPPATH\Models\PagoModel.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\laragon\\www\\pagos\\app\\Models\\PagoModel.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\PagoModel')
 3 APPPATH\Controllers\PagoController.php(12): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\PagoModel')
 4 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\PagoController->__construct()
 5 SYSTEMPATH\CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:13:56 --> ParseError: syntax error, unexpected single-quoted string "created_at", expecting "]"
[Method: GET, Route: pagos/create]
in APPPATH\Models\PagoModel.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\laragon\\www\\pagos\\app\\Models\\PagoModel.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\PagoModel')
 3 APPPATH\Controllers\PagoController.php(12): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\PagoModel')
 4 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\PagoController->__construct()
 5 SYSTEMPATH\CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:13:57 --> ParseError: syntax error, unexpected single-quoted string "created_at", expecting "]"
[Method: GET, Route: pagos]
in APPPATH\Models\PagoModel.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\laragon\\www\\pagos\\app\\Models\\PagoModel.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\PagoModel')
 3 APPPATH\Controllers\PagoController.php(12): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\PagoModel')
 4 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\PagoController->__construct()
 5 SYSTEMPATH\CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:14:03 --> ParseError: syntax error, unexpected single-quoted string "created_at", expecting "]"
[Method: GET, Route: pagos/create]
in APPPATH\Models\PagoModel.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\laragon\\www\\pagos\\app\\Models\\PagoModel.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\PagoModel')
 3 APPPATH\Controllers\PagoController.php(12): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\PagoModel')
 4 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\PagoController->__construct()
 5 SYSTEMPATH\CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:14:03 --> ParseError: syntax error, unexpected single-quoted string "created_at", expecting "]"
[Method: GET, Route: pagos/create]
in APPPATH\Models\PagoModel.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->includeFile('D:\\laragon\\www\\pagos\\app\\Models\\PagoModel.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(272): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\PagoModel')
 3 APPPATH\Controllers\PagoController.php(12): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\PagoModel')
 4 SYSTEMPATH\CodeIgniter.php(903): App\Controllers\PagoController->__construct()
 5 SYSTEMPATH\CodeIgniter.php(500): CodeIgniter\CodeIgniter->createController()
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-28 22:14:26 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\laragon\www\pagos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\pagos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pa...', 0)
#1 D:\laragon\www\pagos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 D:\laragon\www\pagos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 D:\laragon\www\pagos\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 D:\laragon\www\pagos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\laragon\www\pagos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\laragon\www\pagos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\laragon\www\pagos\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\laragon\www\pagos\app\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save(Array)
#9 D:\laragon\www\pagos\system\CodeIgniter.php(933): App\Controllers\PagoController->store()
#10 D:\laragon\www\pagos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
#11 D:\laragon\www\pagos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\laragon\www\pagos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\laragon\www\pagos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\laragon\www\pagos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-28 22:14:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: pagos/store]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:14:26 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:14:26\', \'2024-11-28 22:14:26\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:14:26\', \'2024-11-28 22:14:26\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:14:26 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:14:26\', \'2024-11-28 22:14:26\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:14:26\', \'2024-11-28 22:14:26\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:14:26\', \'2024-11-28 22:14:26\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-28 22:17:54 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\laragon\www\pagos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\pagos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pa...', 0)
#1 D:\laragon\www\pagos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 D:\laragon\www\pagos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 D:\laragon\www\pagos\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 D:\laragon\www\pagos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\laragon\www\pagos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\laragon\www\pagos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\laragon\www\pagos\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\laragon\www\pagos\app\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save(Array)
#9 D:\laragon\www\pagos\system\CodeIgniter.php(933): App\Controllers\PagoController->store()
#10 D:\laragon\www\pagos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
#11 D:\laragon\www\pagos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\laragon\www\pagos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\laragon\www\pagos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\laragon\www\pagos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-28 22:17:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: pagos/store]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:17:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:17:54\', \'2024-11-28 22:17:54\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:17:54\', \'2024-11-28 22:17:54\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:17:54 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:17:54\', \'2024-11-28 22:17:54\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:17:54\', \'2024-11-28 22:17:54\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:17:54\', \'2024-11-28 22:17:54\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-28 22:20:47 --> mysqli_sql_exception: Column 'id_transaccion' cannot be null in D:\laragon\www\pagos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\pagos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pa...', 0)
#1 D:\laragon\www\pagos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 D:\laragon\www\pagos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 D:\laragon\www\pagos\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 D:\laragon\www\pagos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\laragon\www\pagos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\laragon\www\pagos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\laragon\www\pagos\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\laragon\www\pagos\app\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save(Array)
#9 D:\laragon\www\pagos\system\CodeIgniter.php(933): App\Controllers\PagoController->store()
#10 D:\laragon\www\pagos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
#11 D:\laragon\www\pagos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\laragon\www\pagos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\laragon\www\pagos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\laragon\www\pagos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-28 22:20:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id_transaccion' cannot be null
[Method: POST, Route: pagos/store]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:20:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id_transaccion' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:20:47\', \'2024-11-28 22:20:47\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:20:47\', \'2024-11-28 22:20:47\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:20:47 --> [Caused by] mysqli_sql_exception: Column 'id_transaccion' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:20:47\', \'2024-11-28 22:20:47\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:20:47\', \'2024-11-28 22:20:47\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:20:47\', \'2024-11-28 22:20:47\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-28 22:20:51 --> mysqli_sql_exception: Column 'id_transaccion' cannot be null in D:\laragon\www\pagos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\pagos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pa...', 0)
#1 D:\laragon\www\pagos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 D:\laragon\www\pagos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 D:\laragon\www\pagos\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 D:\laragon\www\pagos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\laragon\www\pagos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\laragon\www\pagos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\laragon\www\pagos\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\laragon\www\pagos\app\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save(Array)
#9 D:\laragon\www\pagos\system\CodeIgniter.php(933): App\Controllers\PagoController->store()
#10 D:\laragon\www\pagos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
#11 D:\laragon\www\pagos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\laragon\www\pagos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\laragon\www\pagos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\laragon\www\pagos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-28 22:20:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id_transaccion' cannot be null
[Method: POST, Route: pagos/store]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:20:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id_transaccion' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:20:50\', \'2024-11-28 22:20:50\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:20:50\', \'2024-11-28 22:20:50\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:20:51 --> [Caused by] mysqli_sql_exception: Column 'id_transaccion' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:20:50\', \'2024-11-28 22:20:50\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:20:50\', \'2024-11-28 22:20:50\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:20:50\', \'2024-11-28 22:20:50\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-28 22:24:16 --> mysqli_sql_exception: Column 'id_transaccion' cannot be null in D:\laragon\www\pagos\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\laragon\www\pagos\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pa...', 0)
#1 D:\laragon\www\pagos\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pa...')
#2 D:\laragon\www\pagos\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pa...')
#3 D:\laragon\www\pagos\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pa...', Array, false)
#4 D:\laragon\www\pagos\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\laragon\www\pagos\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\laragon\www\pagos\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\laragon\www\pagos\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\laragon\www\pagos\app\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save(Array)
#9 D:\laragon\www\pagos\system\CodeIgniter.php(933): App\Controllers\PagoController->store()
#10 D:\laragon\www\pagos\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
#11 D:\laragon\www\pagos\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\laragon\www\pagos\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\laragon\www\pagos\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\laragon\www\pagos\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-11-28 22:24:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'id_transaccion' cannot be null
[Method: POST, Route: pagos/store]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:24:16 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'id_transaccion' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:24:16\', \'2024-11-28 22:24:16\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:24:16\', \'2024-11-28 22:24:16\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-28 22:24:16 --> [Caused by] mysqli_sql_exception: Column 'id_transaccion' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:24:16\', \'2024-11-28 22:24:16\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:24:16\', \'2024-11-28 22:24:16\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (\'100\', \'2\', NULL, \'efectivo\', \'2024-11-28 22:24:16\', \'2024-11-28 22:24:16\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pagos` (`cantidad_pagada`, `pedido_id`, `id_transaccion`, `metodo`, `created_at`, `updated_at`) VALUES (:cantidad_pagada:, :pedido_id:, :id_transaccion:, :metodo:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\PagoController.php(49): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PagoController->store()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PagoController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
